# spring:
#  profiles:
#    include: oauth
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/sculptor
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#    properties:
#      hibernate:
#        format_sql: true

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sculptor-db.c78i8e20qx93.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: user_sc
    password: sculptor1!

  # spring data jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create